# docker build -f docker/Dockerfile-neuralangelo -t chenhsuanlin/neuralangelo:23.04-py3 .
# docker push chenhsuanlin/neuralangelo:23.04-py3

# docker run --rm -it --gpus all --shm-size=16g -v D:\projects\neuralangelo\datasets:/data -v D:\projects\neuralangelo:/workspace neuralangelo bash
# torchrun --nproc_per_node=1 train.py --config=projects/neuralangelo/configs/custom/torso.yaml --logdir=/data/logs/torso_experiment

FROM nvcr.io/nvidia/pytorch:25.01-py3
ARG DEBIAN_FRONTEND=noninteractive

# Install basics
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    ffmpeg \
    g++ \
    git \
    libx264-dev \
    python3-setuptools \
    tmux \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Update pip
RUN pip install --upgrade pip setuptools wheel

# Code formatting
RUN pip install --upgrade \
    flake8 \
    pre-commit

# Install base Python libraries for Imaginaire
COPY requirements.txt requirements.txt
ARG FORCE_CUDA=1
ARG TCNN_CUDA_ARCHITECTURES=120;90;89

RUN pip install "cython<3" "numpy<2.0"
RUN pip install PyMCubes==0.1.6 --no-build-isolation
RUN pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch --upgrade --no-cache-dir --no-build-isolation

RUN pip install --upgrade -r requirements.txt
